name: Build Flutter APK with FVM

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

# Add permissions for creating releases
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Set up Dart (without installing Flutter, as FVM will handle it)
      - name: Setup Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      # 3. Install FVM globally
      - name: Install FVM
        run: dart pub global activate fvm

      # 4. Add FVM to PATH
      - name: Add FVM to PATH
        run: echo "$HOME/.pub-cache/bin" >> $GITHUB_PATH

      # 5. Install the Flutter version defined in .fvmrc
      - name: Install Flutter via FVM
        run: fvm install

      # 6. Get dependencies using FVM
      - name: Get dependencies
        run: fvm flutter pub get

      # 7. Build the release APK
      - name: Build release APK
        run: fvm flutter build apk --release

      # 8. Create GitHub Release and Upload APK Asset (only for tagged pushes)
      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: build/app/outputs/flutter-apk/app-release.apk
          token: ${{ secrets.GITHUB_TOKEN }}
