name: Build Flutter APK with FVM

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 1. Add this step to install Flutter/Dart SDK 
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          # Optional: Specify a Flutter version if needed, e.g., '3.19.0' or 'stable'
          # version: '3.19.0' 
          channel: 'stable' 

      - name: Install FVM
        # Dart is now available in the path
        run: dart pub global activate fvm

      - name: Install Flutter via FVM
        run: fvm install

      - name: Get dependencies
        run: fvm flutter pub get

      - name: Build release APK
        run: fvm flutter build apk --release

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk